[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/img/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.HTML"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
